package com.ssm.entity;

import java.io.Serializable;
import java.util.Date;

public class Book implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column emp_tbl.emp_id
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	private Integer empId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column emp_tbl.emp_title
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	private String empTitle;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column emp_tbl.emp_author
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	private String empAuthor;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column emp_tbl.hire_date
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	private Date hireDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column emp_tbl.emp_id
	 *
	 * @return the value of emp_tbl.emp_id
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	public Integer getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column emp_tbl.emp_id
	 *
	 * @param empId the value for emp_tbl.emp_id
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column emp_tbl.emp_title
	 *
	 * @return the value of emp_tbl.emp_title
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	public String getEmpTitle() {
		return empTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column emp_tbl.emp_title
	 *
	 * @param empTitle the value for emp_tbl.emp_title
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	public void setEmpTitle(String empTitle) {
		this.empTitle = empTitle == null ? null : empTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column emp_tbl.emp_author
	 *
	 * @return the value of emp_tbl.emp_author
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	public String getEmpAuthor() {
		return empAuthor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column emp_tbl.emp_author
	 *
	 * @param empAuthor the value for emp_tbl.emp_author
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	public void setEmpAuthor(String empAuthor) {
		this.empAuthor = empAuthor == null ? null : empAuthor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column emp_tbl.hire_date
	 *
	 * @return the value of emp_tbl.hire_date
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	public Date getHireDate() {
		return hireDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column emp_tbl.hire_date
	 *
	 * @param hireDate the value for emp_tbl.hire_date
	 *
	 * @mbg.generated Wed Jul 03 00:33:18 CST 2019
	 */
	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	@Override
	public String toString() {
		return "Book [empId=" + empId + ", empTitle=" + empTitle + ", empAuthor=" + empAuthor + ", hireDate=" + hireDate
				+ "]";
	}

}