package com.ssm.dao;

import java.util.List;

import com.ssm.entity.Book;

public interface BookMapper {
	
	
	List<Book> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 03 00:33:18 CST 2019
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 03 00:33:18 CST 2019
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 03 00:33:18 CST 2019
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 03 00:33:18 CST 2019
     */
    Book selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 03 00:33:18 CST 2019
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 03 00:33:18 CST 2019
     */
    int updateByPrimaryKey(Book record);
}